### ISSUE TITLE
Error when bash 1_gce-standup.sh

### ISSUE THREAD

**Issue by deb0612** [lynnlangit/TeamTeri#9]
When setup Galaxy VMs
I use $bash 1_gce-standup.sh command
something wrong!
------------------------
deb0612@cloudshell:~/TeamTeri/Galaxy/Setup_VMs (galaxy-test-project-250916)$ bash 1_gce-standup.sh
Importing configuration from cli.rc...
./0_cli.rc: line 1: syntax error near unexpected token `newline'
./0_cli.rc: line 1: `ACCOUNT=<account_email>'
authenticate to GCP from your working directory via Terminal
will not launch if  already has credentials

You are already authenticated with gcloud when running
inside the Cloud Shell and so do not need to run this
command. Do you wish to proceed anyway?

Do you want to continue (Y/n)?  Y

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?code_challenge=fShCtOGMhFd92W9mwBqpRdLVO9d_a5LgKqf245aLEr8&prompt=select_account&code_challenge_method=S256&access_type=offline&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth

Enter verification code: 4/qQEEP8bQWudtvgKyY-yMfI4HUeph9tLdQvkQOkk8oo2WigUiMQjQDSc
Creating firewall rule...
Creating client image, please wait...
Waiting for image to become available...
ERROR: (gcloud.compute.firewall-rules.create) argument --target-tags: expected one argument
Usage: gcloud compute firewall-rules create NAME (--action=ACTION | --allow=PROTOCOL[:PORT[-PORT]],[...]) [optional flags]
  optional flags may be  --action | --allow | --description |
                         --destination-ranges | --direction | --disabled |
                         --enable-logging | --help | --network | --priority |
                         --rules | --source-ranges | --source-service-accounts |
                         --source-tags | --target-service-accounts |
                         --target-tags
For detailed information on this command and its flags, run:
  gcloud compute firewall-rules create --help
ERROR: (gcloud.compute.images.create) argument --project: expected one argument
Usage: gcloud compute images create IMAGE_NAME (--source-disk=SOURCE_DISK | --source-image=SOURCE_IMAGE | --source-image-family=SOURCE_IMAGE_FAMILY | --source-snapshot=SOURCE_SNAPSHOT | --source-uri=SOURCE_URI) [optional flags]
  optional flags may be  --csek-key-file | --description | --family | --force |
                         --guest-os-features | --help | --kms-key |
                         --kms-keyring | --kms-location | --kms-project |
                         --labels | --licenses | --require-csek-key-create |
                         --source-disk | --source-disk-zone | --source-image |
                         --source-image-family | --source-image-project |
                         --source-snapshot | --source-uri

For detailed information on this command and its flags, run:
  gcloud compute images create --help
Creating client instances, please wait...
Waiting for instances to become available...
ERROR: (gcloud.compute.instances.create) argument --machine-type: expected one argument
ERROR: (gcloud.compute.instances.create) argument --machine-type: expected one argument
Usage: gcloud compute instances create INSTANCE_NAMES [INSTANCE_NAMES ...] [optional flags]
  optional flags may be  --accelerator | --address | --no-address | --async |
                         --boot-disk-auto-delete | --boot-disk-device-name |
                         --boot-disk-kms-key | --boot-disk-kms-keyring |
                         --boot-disk-kms-location | --boot-disk-kms-project |
                         --boot-disk-size | --boot-disk-type |
                         --can-ip-forward | --create-disk | --csek-key-file |
                         --custom-cpu | --custom-extensions | --custom-memory |
                         --custom-vm-type | --deletion-protection |
                         --description | --disk | --help | --hostname |
                         --image | --image-family | --image-project | --labels |
                         --local-ssd | --machine-type | --maintenance-policy |
                         --metadata | --metadata-from-file |
                         --min-cpu-platform | --network | --network-interface |
                         --network-tier | --node | --node-affinity-file |
                         --node-group | --preemptible | --private-network-ip |
                         --node-group | --preemptible | --private-network-ip |
                         --public-ptr | --no-public-ptr | --public-ptr-domain |
                         --no-public-ptr-domain | --require-csek-key-create |
                         --restart-on-failure | --scopes | --no-scopes |
                         --service-account | --no-service-account |
                         --shielded-integrity-monitoring |
For detailed information on this command and its flags, run:
  gcloud compute instances create --help
-----------------------------------------------

**Comment by lynnlangit** [comment]
Hello - in the `0_cli.rc` file, you should first edit that file to change all of the lines 1 and 2 with <xxx> to your GCP account file info.  Also you may need to change the values in lines 4-10 depending on in which GCP region you wish to start your VM, what disk size, etc...

**Comment by deb0612** [comment]
Dear Lynn,
I had followed your instruction.
There is another error showed in attachment picture.

Lynn Langit <notifications@github.com> 於 2019年8月26日 週一 下午9:58寫道：
